# offline test
env:
  n_games: 100
  env_name: "BreakoutNoFrameskip-v4"

algo:
  algo: "ScaledQAgent"
  epochs: 100
  n_norm_groups: 4
  alpha: 0.1
  gamma: 0.99
  epsilon: 0.01
  lr: 1.e-4
  eps: 1.e-6
  mem_size: 10000
  eps_min: 0.01
  batch_size: 32
  replace: 2000
  eps_dec: 1.e-5
  v_min: -20.0
  v_max: 20.0
  atoms: 51

util:
  load_checkpoint: True
  seed: 42
  make_video: False
  gpu: "0"
  chkpt_dir: "models/scaled"
  video_dir: "video"
  log_dir: "log"
  save_memory: False
  memory_dir: "memory"
  data_dir: "./memory/2024-04-17_DQNAgent_BreakoutNoFrameskip-v4_lr0.00025__45000games"
  log_file: "./log/2024-04-17_DQNAgent_BreakoutNoFrameskip-v4_lr0.00025__45000games.csv"
  